### ISSUE TITLE
Publish Alexa Skills

### ISSUE THREAD

**Issue by kcrw** [KCRW-org/KCRW-Alexa-Skill#7]
Juan: @alecpm  We've activated the skills you sent over on our device but have not tested as thoroughly as we want- besides testing those two, what more needs to be done before we publish on the amazon skill store for the on air and E24 streams?

**Comment by alecpm** [comment]
I think more testing is a good idea. From my perspective and testing, it's ready to go for the live streams. It's possible that in testing we'll discover some specific things (e.g. breaking on strange characters in song names, or just pronouncing them funny). We should be able to test and push changes quickly (all code is on the server side).

Right now the "KCRW Beta" skill and "KCRW" skill are identical, but "KCRW Beta" will never be published and can be used for testing new features and functionality. I know a few people with Echos who may be willing to test out the app in beta if you'd like to expand to a larger test pool (I'm sure there are people at the station too).

**Comment by alecpm** [comment]
I think someone from the station should probably provide some copy for the short and long description here:

https://developer.amazon.com/edw/home.html#/skill/amzn1.ask.skill.1a8abcbc-1fca-4f61-b87e-12da026087ce/en_US/publishingInfo

Then we can submit for publication.

**Comment by kcrw** [comment]
Juan: short and descriptions have been added - can always be pulled from http://www.kcrw.com/about if needed in the future

**Comment by alecpm** [comment]
I think we really need something specific to the skill for these rather than generic about KCRW info.

**Comment by alecpm** [comment]
This info will appear in the amazon skills "store" page for the skill. For an example see: https://alexa.amazon.com/spa/index.html#skills/dp/B019G0M2WS/?ref=skill_dsk_tes_gw_3

**Comment by juanbonigno** [comment]
@alecpm  we were doing some testing today - we are going to want 'play e24' and 'play eclectic 24' to automatically start our e24 stream. @seankcrw mentioned we may have to create a separate account within amazon store to accomplish this? think its worth it if thats the only way to achieve it. 'play kcrw' command works great. thanks

**Comment by alecpm** [comment]
We don't need a second account, be we'd need a second skill with the new name "Eclectic24". If you wanted "play e24" to work then you'd need a third skill. Basically, "play" is an alias for "open" and only works with a skill's "invocation name," and a skill can only have one "invocation name".

"play" is also an internal action that searches for content on the internal Amazon services, so "Play Eclectic24" will use TuneIn or iHeart unless there's a skill with the invocation name "Eclectic24".

The main hurdle to having multiple skills is that people will need to manually install a separate, but effectively, identical skill for each name that you want them to be able to say "play xxxx" for. That's a pretty big annoyance, and definitely not something I've seen other skills do.

There's more info on invocation names, choosing them and using them here:

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/choosing-the-invocation-name-for-an-alexa-skill

**Comment by alecpm** [comment]
I think it's also important to keep in mind that Echo users who use custom skills are generally already used to this "invocation name" strangeness and expect to say "Alexa, ask _APP-NAME_ ..." or similar for custom skills.  That's how all skills work unless they control Smart Home devices or provide a Flash News Briefing. So "Ask KCRW to play Eclectic24" is a much more standard Echo way of doing things than "Play Eclectic24" is. The latter command would generally be expected to search Amazon Music + TuneIn + ..., rather than use a custom skill.

**Comment by alecpm** [comment]
This document also provides some important background: https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/supported-phrases-to-begin-a-conversation

I'm also a little concerned that if we start trying to publish multiple identical apps with different invocation names, we'll end up blacklisted as app store spam or similar.

**Comment by juanbonigno** [comment]
@alecpm @seankcrw currently "Alexa play KCRW" is pulling from TuneIn, also "Alexa play KCRW" is pulling from iHeart. Is this the expected behavior? We asked SGs to set up aliases a while back but i'm not sure if we mapped them to the skills

For Alexa KCRW On Air:

kcrw.streamguys1.com/kcrw_192k_mp3_on_air-alexa
kcrw.streamguys1.com/kcrw_128k_mp3_on_air-alexa
kcrw.streamguys1.com/kcrw_128k_aac_on_air-alexa

For Alexa KCRW Eclectic 24:

kcrw.streamguys1.com/kcrw_192k_mp3_e24-alexa
kcrw.streamguys1.com/kcrw_128k_mp3_e24-alexa
kcrw.streamguys1.com/kcrw_128k_aac_e24-alexa
